name: Check PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]


jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
 

      - name: PR Title Validation
        shell: bash
        run: |
          set -euo pipefail

          echo "Actor: ${{ github.actor }}"
